const DAYS=["2026-10-16","2026-10-17","2026-10-18"];
const PARK={dlp:"Disneyland Park",daw:"Disney Adventure World"};
const LAND_ORDER={dlp:["Main Street U.S.A.","Adventureland","Frontierland","Fantasyland","Discoveryland"],daw:["World Premiere Plaza","Adventure Way","Worlds of Pixar","Avengers Campus","World of Frozen"]};
const CATALOG=[
// Disneyland Park — current official attraction catalog, including closed items
["dlp","attraction","Main Street U.S.A.","Main Street Vehicles"],["dlp","attraction","Main Street U.S.A.","Disneyland Railroad Main Street Station"],["dlp","attraction","Main Street U.S.A.","Discovery Arcade"],["dlp","attraction","Main Street U.S.A.","Liberty Arcade"],["dlp","attraction","Main Street U.S.A.","Horse-Drawn Streetcars"],
["dlp","attraction","Adventureland","Adventure Isle"],["dlp","attraction","Adventureland","Alice's Curious Labyrinth"],["dlp","attraction","Adventureland","Indiana Jones™ and the Temple of Peril"],["dlp","attraction","Adventureland","La Cabane des Robinson"],["dlp","attraction","Adventureland","Le Passage Enchanté d'Aladdin"],["dlp","attraction","Adventureland","Pirates of the Caribbean"],["dlp","attraction","Adventureland","Pirate Galleon"],["dlp","attraction","Adventureland","Pirates' Beach"],
["dlp","attraction","Frontierland","Big Thunder Mountain"],["dlp","attraction","Frontierland","Phantom Manor"],["dlp","attraction","Frontierland","Thunder Mesa Riverboat Landing"],["dlp","attraction","Frontierland","Rustler Roundup Shootin' Gallery"],["dlp","attraction","Frontierland","Frontierland Playground"],
["dlp","attraction","Fantasyland","Peter Pan's Flight"],["dlp","attraction","Fantasyland","it's a small world"],["dlp","attraction","Fantasyland","Blanche-Neige et les Sept Nains®"],["dlp","attraction","Fantasyland","Les Voyages de Pinocchio"],["dlp","attraction","Fantasyland","Dumbo the Flying Elephant"],["dlp","attraction","Fantasyland","Casey Jr. – le Petit Train du Cirque"],["dlp","attraction","Fantasyland","Le Pays des Contes de Fées, presented by Vittel"],["dlp","attraction","Fantasyland","Le Carrousel de Lancelot"],["dlp","attraction","Fantasyland","La Tanière du Dragon"],["dlp","attraction","Fantasyland","Sleeping Beauty Castle"],["dlp","attraction","Fantasyland","La Galerie de la Belle au Bois Dormant"],["dlp","attraction","Fantasyland","Mad Hatter's Tea Cups"],["dlp","attraction","Fantasyland","Princess Pavilion"],
["dlp","attraction","Discoveryland","Star Wars Hyperspace Mountain"],["dlp","attraction","Discoveryland","Buzz Lightyear Laser Blast"],["dlp","attraction","Discoveryland","Star Tours: The Adventures Continue*"],["dlp","attraction","Discoveryland","Orbitron®"],["dlp","attraction","Discoveryland","Autopia, presented by Avis"],["dlp","attraction","Discoveryland","Les Mystères du Nautilus"],
// Disney Adventure World — current 2026 catalog
["daw","attraction","World Premiere Plaza","The Twilight Zone Tower of Terror"],["daw","attraction","World Premiere Plaza","World Premiere"],["daw","attraction","World Premiere Plaza","Les Tapis Volants - Flying Carpets Over Agrabah®"],["daw","attraction","Adventure Way","Raiponce Tangled Spin"],["daw","attraction","Worlds of Pixar","Ratatouille : L’Aventure Totalement Toquée de Rémy"],["daw","attraction","Worlds of Pixar","Crush's Coaster"],["daw","attraction","Worlds of Pixar","Cars ROAD TRIP"],["daw","attraction","Worlds of Pixar","Cars Quatre Roues Rallye"],["daw","attraction","Worlds of Pixar","Slinky® Dog Zigzag Spin"],["daw","attraction","Worlds of Pixar","RC Racer"],["daw","attraction","Worlds of Pixar","Toy Soldiers Parachute Drop"],["daw","attraction","Avengers Campus","Spider-Man W.E.B. Adventure"],["daw","attraction","Avengers Campus","Avengers Assemble: Flight Force"],["daw","attraction","Avengers Campus","Hero Training Center"],["daw","attraction","World of Frozen","Frozen Ever After"],
// Shows / entertainment
["dlp","show","Entertainment","Disney Stars on Parade"],["dlp","show","Entertainment","Disney Tales of Magic"],["dlp","show","Entertainment","The Lion King: Rhythms of the Pride Lands"],["dlp","show","Entertainment","Mickey and the Magician"],["dlp","show","Entertainment","Seasonal Halloween Entertainment"],
["daw","show","Entertainment","Disney Princess Cavalcade"],["daw","show","Entertainment","A Celebration in Arendelle"],["daw","show","Entertainment","TOGETHER: a Pixar Musical Adventure"],["daw","show","Entertainment","Marvel Avengers Campus Live Action Entertainment"],["daw","show","Entertainment","Disney Marching Band"],["daw","show","Entertainment","A Musical Moment with Rapunzel and Flynn"],["daw","show","Entertainment","Disney Cascade of Lights"],
// Character experiences
["dlp","character","Character Encounters","Meet Mickey Mouse"],["dlp","character","Character Encounters","Princess Pavilion"],["dlp","character","Character Encounters","Star Wars Character Encounter"],["dlp","character","Character Encounters","Classic Disney Character Encounters"],["dlp","character","Character Encounters","Meet Jack Skellington and Sally"],["dlp","character","Character Encounters","Meet Winnie the Pooh"],["dlp","character","Character Encounters","Meet Goofy"],
["daw","character","Character Encounters","Marvel Super Hero Encounters"],["daw","character","Character Encounters","Hero Training Center"],["daw","character","Character Encounters","Pixar Character Encounters"],["daw","character","Character Encounters","Woody / Toy Story Characters"],["daw","character","Character Encounters","Elsa & Anna — Rencontre Royale"]
].map((x,i)=>({id:`${x[0]}-${x[1]}-${i}`,park:x[0],category:x[1],land:x[2],name:x[3]}));
const CLOSED=["Crush's Coaster","La Galerie de la Belle au Bois Dormant","Mad Hatter's Tea Cups","Pirate Galleon","Pirates' Beach"]; // current official page status at build time; update if DLP changes
const ALIASES={"Avengers Assemble: Flight Force":["Flight Force"],"Spider-Man W.E.B. Adventure":["Spider-Man W.E.B. Adventure","Spider-Man W.E.B. Adventure*"],"The Twilight Zone Tower of Terror":["The Twilight Zone Tower of Terror™","Tower of Terror"],"Ratatouille : L’Aventure Totalement Toquée de Rémy":["Ratatouille: The Adventure"],"Star Wars Hyperspace Mountain":["Star Wars Hyperspace Mountain","Hyperspace Mountain"],"it's a small world":["\"it's a small world\""],"Slinky® Dog Zigzag Spin":["Slinky Dog Zigzag Spin"],"The Lion King: Rhythms of the Pride Lands":["The Lion King: Rhythms of the Pride Lands"]};
const STORE="dlp_map_checked_v4";let checked=JSON.parse(localStorage.getItem(STORE)||"{}");let activeDay=localStorage.getItem("dlp_map_day")||"trip";let waits={};let dataUpdated=null;let view="map";
function norm(s){return String(s||"").toLowerCase().replace(/[™®’'“”\".:,!?–—-]/g," ").replace(/\s+/g," ").trim()}
function isDone(r){if(activeDay==="trip")return DAYS.some(d=>!!checked[d]?.[r.id]);return !!checked[activeDay]?.[r.id]}
function save(){localStorage.setItem(STORE,JSON.stringify(checked));localStorage.setItem("dlp_map_day",activeDay)}
function toggle(r){if(!checked[activeDay])checked[activeDay]={};if(activeDay==="trip"){DAYS.forEach(d=>{if(!checked[d])checked[d]={};checked[d][r.id]=!isDone(r)});}else checked[activeDay][r.id]=!checked[activeDay][r.id];save();renderAll();toast(isDone(r)?"Marked complete ✓":"Marked incomplete")}
function waitFor(r){const candidates=[r.name,...(ALIASES[r.name]||[])].map(norm);const key=Object.keys(waits).find(k=>candidates.some(c=>norm(k)===c||norm(k).includes(c)||c.includes(norm(k))));return key?waits[key]:null}
function status(r){if(r.category!=="attraction")return "event";if(CLOSED.includes(r.name))return "closed";const w=waitFor(r);if(!w)return "nodata";if(w.closed===true||w.is_open===false)return "closed";const n=Number(w.wait??w.wait_time);if(!Number.isFinite(n))return "nodata";return n<=20?"green":n<=45?"yellow":n<=70?"orange":"red"}
function waitText(r){if(r.category!=="attraction")return "EVENT";const s=status(r);if(s==="closed")return "CLOSED";const w=waitFor(r);if(!w)return "—";const n=Number(w.wait??w.wait_time);return Number.isFinite(n)?`${n}m`:"—"}
function filtered(){const p=document.getElementById("park").value,t=document.getElementById("type").value,s=document.getElementById("state").value,q=norm(document.getElementById("search").value);return CATALOG.filter(r=>(p==="all"||r.park===p)&&(t==="all"||r.category===t)&&(!q||norm(r.name).includes(q)||norm(r.land).includes(q)||norm(r.category).includes(q))).filter(r=>{if(s==="done")return isDone(r);if(s==="todo")return !isDone(r);if(s==="closed")return status(r)==="closed";if(s==="live")return ["green","yellow","orange","red"].includes(status(r));return true})}
const svg=document.getElementById("map");
const LAYOUT={dlp:{x:20,y:20,w:550,h:700},daw:{x:630,y:20,w:550,h:700}};
const LANDS={
"dlp|Main Street U.S.A.":{x:35,y:80,w:150,h:250,fill:"#e8e0f4"},"dlp|Adventureland":{x:200,y:330,w:175,h:180,fill:"#d8eddc"},"dlp|Frontierland":{x:35,y:330,w:150,h:180,fill:"#f5dfc6"},"dlp|Fantasyland":{x:200,y:80,w:340,h:235,fill:"#dceafa"},"dlp|Discoveryland":{x:385,y:330,w:155,h:180,fill:"#d9e4e9"},
"daw|World Premiere Plaza":{x:645,y:80,w:150,h:190,fill:"#e8e0f4"},"daw|Adventure Way":{x:810,y:80,w:110,h:430,fill:"#e8edcf"},"daw|Worlds of Pixar":{x:935,y:80,w:220,h:250,fill:"#f8dfc7"},"daw|Avengers Campus":{x:645,y:290,w:150,h:220,fill:"#dce2ef"},"daw|World of Frozen":{x:935,y:350,w:220,h:250,fill:"#d7edf2"}}
function parkShape(p){const a=LAYOUT[p];return `<rect class="park" x="${a.x}" y="${a.y}" width="${a.w}" height="${a.h}" rx="30" fill="${p==="dlp"?"#fbfaf7":"#f8fbff"}"/><text class="park-label" x="${a.x+18}" y="${a.y+38}">${PARK[p]}</text>`}
function landProgress(park,land){const rs=CATALOG.filter(r=>r.park===park&&r.land===land);const d=rs.filter(isDone).length;return [d,rs.length]}
function markerPos(r,index){const l=LANDS[`${r.park}|${r.land}`];if(!l)return [50,50];const rs=CATALOG.filter(x=>x.park===r.park&&x.land===r.land);const i=rs.findIndex(x=>x.id===r.id);const cols=l.w<140?2:3;const rows=Math.ceil(rs.length/cols);const cellW=l.w/(cols+1),cellH=Math.max(34,(l.h-55)/(rows+1));return [l.x+cellW*((i%cols)+1),l.y+52+cellH*(Math.floor(i/cols)+1)]}
function renderMap(){let out=parkShape("dlp")+parkShape("daw");Object.entries(LANDS).forEach(([k,l])=>{const [p,land]=k.split("|");const [d,total]=landProgress(p,land);const pct=total?Math.round(d/total*100):0;out+=`<g><rect class="land" x="${l.x}" y="${l.y}" width="${l.w}" height="${l.h}" rx="18" fill="${l.fill}"/><rect x="${l.x+2}" y="${l.y+2+l.h*(1-pct/100)}" width="${l.w-4}" height="${Math.max(0,l.h*pct/100-2)}" rx="15" fill="#16a34a" opacity=".20"/><text class="land-label" x="${l.x+10}" y="${l.y+22}">${land}</text><text class="land-count" x="${l.x+10}" y="${l.y+38}">${d}/${total} complete • ${pct}%</text></g>`});filtered().forEach((r,i)=>{const [x,y]=markerPos(r,i),s=status(r),done=isDone(r),wt=waitText(r),cls=done?"done":s==="nodata"?"no-data":s==="closed"?"closed":s==="event"?"no-data":"live-"+s;const glyph=done?"✓":r.category!=="attraction"?"★":wt==="—"?"—":wt.replace("m","");out+=`<g class="marker ${cls}" data-id="${r.id}" transform="translate(${x} ${y})" tabindex="0" role="button" aria-label="${esc(r.name)} — ${esc(wt)}"><circle class="hit" r="22"/><rect class="box" x="-15" y="-15" width="30" height="30" rx="8"/><text>${glyph}</text><text class="marker-label" y="26">${esc(short(r.name))}</text></g>`});svg.innerHTML=out;svg.querySelectorAll(".marker").forEach(g=>{g.addEventListener("click",()=>openDrawer(g.dataset.id));g.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")openDrawer(g.dataset.id)})})}
function short(s){const words=s.replace(/[™®]/g,"").split(" ");return words.length>3?words.slice(0,3).join(" ")+"…":s}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function renderList(){const el=document.getElementById("list");el.innerHTML=filtered().map(r=>`<article class="list-card" data-id="${r.id}"><input class="cb" type="checkbox" ${isDone(r)?"checked":""}><div class="main"><div class="name">${esc(r.name)}</div><div class="sub">${PARK[r.park]} • ${esc(r.land)} • ${r.category}</div></div><span class="wait ${status(r)}">${waitText(r)}${r.category==="attraction"&&waitFor(r)?"<small>LIVE</small>":""}</span></article>`).join("")||"<div class='list-card'>Nothing matches.</div>";el.querySelectorAll(".list-card").forEach(c=>{const r=CATALOG.find(x=>x.id===c.dataset.id);c.querySelector(".cb").addEventListener("click",e=>{e.stopPropagation();toggle(r)});c.addEventListener("click",e=>{if(!e.target.classList.contains("cb"))openDrawer(r.id)})})}
function renderChecklist(){const el=document.getElementById("checklist"),rows=filtered(),done=CATALOG.filter(isDone).length;document.getElementById("summary").textContent=`${done} of ${CATALOG.length} experiences completed • ${CATALOG.length-done} remaining`;el.innerHTML=rows.map(r=>`<article class="check-card"><input class="cb" data-id="${r.id}" type="checkbox" ${isDone(r)?"checked":""}><div class="main"><div class="name">${esc(r.name)}</div><div class="sub">${PARK[r.park]} • ${esc(r.land)} • ${r.category}</div></div><span class="wait ${status(r)}">${waitText(r)}</span></article>`).join("");el.querySelectorAll(".cb").forEach(cb=>cb.addEventListener("change",()=>toggle(CATALOG.find(r=>r.id===cb.dataset.id))))}
function renderStats(){const all=CATALOG.length,done=CATALOG.filter(isDone).length,live=CATALOG.filter(r=>["green","yellow","orange","red"].includes(status(r))).length,closed=CATALOG.filter(r=>status(r)==="closed").length;document.getElementById("stats").innerHTML=[[all,"experiences"],[done,"completed"],[live,"live waits"],[closed,"currently closed"]].map(x=>`<div class="stat"><b>${x[0]}</b><small>${x[1]}</small></div>`).join("")}
function renderAll(){renderStats();if(view==="map")renderMap();if(view==="list")renderList();if(view==="checklist")renderChecklist();document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));["map","list","checklist","trip"].forEach(v=>document.getElementById(v+"View").classList.toggle("hidden",view!==v))}
function openDrawer(id){const r=CATALOG.find(x=>x.id===id);if(!r)return;const s=status(r);document.getElementById("drawerBody").innerHTML=`<h2>${esc(r.name)}</h2><div class="meta">${PARK[r.park]} • ${esc(r.land)} • ${r.category}</div><div class="big ${s}">${esc(waitText(r))}</div><button class="complete" id="drawerComplete">${isDone(r)?"✓ Completed — tap to undo":"Mark complete"}</button>`;document.getElementById("drawer").classList.remove("hidden");document.getElementById("drawerComplete").onclick=()=>{toggle(r);openDrawer(r.id)}}
document.getElementById("close").onclick=()=>document.getElementById("drawer").classList.add("hidden");
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1200)}
function applyFilters(){renderAll()}
["day","park","type","state","search"].forEach(id=>document.getElementById(id).addEventListener(id==="search"?"input":"change",()=>{if(id==="day"){activeDay=document.getElementById("day").value;save()}applyFilters()}));
document.querySelectorAll(".tabs button").forEach(b=>b.addEventListener("click",()=>{view=b.dataset.view;renderAll()}));
document.getElementById("reset").onclick=()=>{if(confirm("Reset completion for this selected day/view?")){if(activeDay==="trip")checked={};else checked[activeDay]={};save();renderAll()}};
document.getElementById("refresh").onclick=loadWaits;
async function loadWaits(){document.getElementById("updated").textContent="Refreshing…";try{const urls=["https://queue-times.com/parks/4/queue_times.json?ts="+Date.now(),"https://queue-times.com/parks/28/queue_times.json?ts="+Date.now()];const rs=await Promise.all(urls.map(u=>fetch(u,{cache:"no-store"})));if(rs.some(r=>!r.ok))throw new Error("Queue-Times request failed");const js=await Promise.all(rs.map(r=>r.json()));waits={};js.forEach(j=>(j.lands||[]).forEach(l=>(l.rides||[]).forEach(x=>{waits[x.name]={wait:x.wait_time,is_open:x.is_open,closed:x.is_open===false,last_updated:x.last_updated}})));dataUpdated=js.flatMap(j=>(j.lands||[]).flatMap(l=>(l.rides||[]).map(x=>x.last_updated).filter(Boolean))).sort().pop()||new Date().toISOString();document.getElementById("source").innerHTML='Wait source: <a href="https://queue-times.com/" target="_blank" rel="noopener">Queue-Times.com</a>';document.getElementById("updated").textContent="Updated "+new Date(dataUpdated).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"});renderAll();document.getElementById("progress").style.animation="none";void document.getElementById("progress").offsetWidth;document.getElementById("progress").style.animation="shrink 300s linear forwards"}catch(e){document.getElementById("updated").textContent="Live wait feed unavailable";document.getElementById("source").innerHTML='Wait source: <a href="https://queue-times.com/" target="_blank" rel="noopener">Queue-Times.com</a> • checklist still works';renderAll()}}
// Keep the map lightweight: no Google Maps, Leaflet, tiles, or external JS libraries.
if(DAYS.includes(activeDay))document.getElementById("day").value=activeDay;else document.getElementById("day").value="trip";
loadWaits();setInterval(loadWaits,300000);renderAll();
